/**
 * Audit action catalogue. Every audit_events.action value comes from here. Actions flagged `custody`
 * form the digital chain of custody for an evidence item (audit_events.evidence_id is set).
 */
export const AUDIT_CATEGORIES = [
  'AUTH', 'ADMIN', 'EVIDENCE', 'CUSTODY', 'MEDIA', 'AI', 'REVIEW', 'SEARCH', 'INVESTIGATION', 'CASE',
  'EXPORT', 'SHARE', 'INTEGRATION', 'SECURITY', 'SYSTEM', 'REPORT',
] as const;
export type AuditCategory = (typeof AUDIT_CATEGORIES)[number];
export type AuditOutcome = 'SUCCESS' | 'FAILURE' | 'DENIED';
export type AuditActorType = 'USER' | 'SYSTEM' | 'API_CLIENT' | 'EXTERNAL_RECIPIENT';

export const AUDIT_ACTIONS = {
  // Auth / session
  LOGIN: { category: 'AUTH', custody: false },
  LOGIN_FAILED: { category: 'AUTH', custody: false },
  LOGOUT: { category: 'AUTH', custody: false },
  MFA_CHALLENGE_PASSED: { category: 'AUTH', custody: false },
  MFA_CHALLENGE_FAILED: { category: 'AUTH', custody: false },
  MFA_ENROLLED: { category: 'AUTH', custody: false },
  MFA_DISABLED: { category: 'AUTH', custody: false },
  PASSWORD_CHANGED: { category: 'AUTH', custody: false },
  TOKEN_REFRESHED: { category: 'AUTH', custody: false },
  TOKEN_REUSE_DETECTED: { category: 'SECURITY', custody: false },
  SESSION_REVOKED: { category: 'AUTH', custody: false },
  ACCOUNT_LOCKED: { category: 'SECURITY', custody: false },
  ACCESS_DENIED: { category: 'SECURITY', custody: false },
  RATE_LIMITED: { category: 'SECURITY', custody: false },
  API_CLIENT_AUTHENTICATED: { category: 'AUTH', custody: false },
  // Administration
  USER_CREATED: { category: 'ADMIN', custody: false },
  USER_UPDATED: { category: 'ADMIN', custody: false },
  USER_STATUS_CHANGED: { category: 'ADMIN', custody: false },
  USER_PASSWORD_RESET: { category: 'ADMIN', custody: false },
  USER_MFA_RESET: { category: 'ADMIN', custody: false },
  USER_UNLOCKED: { category: 'ADMIN', custody: false },
  /** An administrative change refused by a security rule (privilege escalation, SoD, self-modification). */
  ADMIN_ACTION_DENIED: { category: 'SECURITY', custody: false },
  ROLE_CREATED: { category: 'ADMIN', custody: false },
  ROLE_UPDATED: { category: 'ADMIN', custody: false },
  ROLE_DELETED: { category: 'ADMIN', custody: false },
  ROLE_GRANTED: { category: 'ADMIN', custody: false },
  ROLE_REVOKED: { category: 'ADMIN', custody: false },
  ORG_UNIT_CREATED: { category: 'ADMIN', custody: false },
  ORG_UNIT_UPDATED: { category: 'ADMIN', custody: false },
  DEVICE_REGISTERED: { category: 'ADMIN', custody: false },
  DEVICE_UPDATED: { category: 'ADMIN', custody: false },
  DEVICE_ASSIGNED: { category: 'ADMIN', custody: false },
  DEVICE_UNASSIGNED: { category: 'ADMIN', custody: false },
  DEVICE_RETIRED: { category: 'ADMIN', custody: false },
  SETTINGS_UPDATED: { category: 'ADMIN', custody: false },
  RETENTION_POLICY_CHANGED: { category: 'ADMIN', custody: false },
  API_CLIENT_CREATED: { category: 'ADMIN', custody: false },
  API_CLIENT_REVOKED: { category: 'ADMIN', custody: false },
  INTEGRATION_CONFIGURED: { category: 'INTEGRATION', custody: false },
  // Ingestion & registration (custody)
  UPLOAD_INITIATED: { category: 'EVIDENCE', custody: false },
  UPLOAD_COMPLETED: { category: 'CUSTODY', custody: true },
  UPLOAD_ABORTED: { category: 'EVIDENCE', custody: false },
  UPLOAD_FAILED: { category: 'EVIDENCE', custody: false },
  EVIDENCE_RECEIVED: { category: 'CUSTODY', custody: true },
  EVIDENCE_VALIDATED: { category: 'CUSTODY', custody: true },
  EVIDENCE_VALIDATION_FAILED: { category: 'CUSTODY', custody: true },
  EVIDENCE_HASHED: { category: 'CUSTODY', custody: true },
  EVIDENCE_QUARANTINED: { category: 'CUSTODY', custody: true },
  EVIDENCE_QUARANTINE_RELEASED: { category: 'CUSTODY', custody: true },
  EVIDENCE_REJECTED: { category: 'CUSTODY', custody: true },
  EVIDENCE_DUPLICATE_DETECTED: { category: 'CUSTODY', custody: true },
  EVIDENCE_REGISTERED: { category: 'CUSTODY', custody: true },
  EVIDENCE_STORED: { category: 'CUSTODY', custody: true },
  EVIDENCE_METADATA_EXTRACTED: { category: 'CUSTODY', custody: true },
  EVIDENCE_METADATA_UPDATED: { category: 'CUSTODY', custody: true },
  EVIDENCE_TAGGED: { category: 'CUSTODY', custody: true },
  EVIDENCE_VIEWED: { category: 'CUSTODY', custody: true },
  EVIDENCE_PLAYED: { category: 'CUSTODY', custody: true },
  EVIDENCE_DOWNLOADED: { category: 'CUSTODY', custody: true },
  EVIDENCE_SNAPSHOT_CREATED: { category: 'CUSTODY', custody: true },
  EVIDENCE_INTEGRITY_VERIFIED: { category: 'CUSTODY', custody: true },
  EVIDENCE_INTEGRITY_FAILED: { category: 'CUSTODY', custody: true },
  EVIDENCE_TIER_CHANGED: { category: 'CUSTODY', custody: true },
  EVIDENCE_LEGAL_HOLD_SET: { category: 'CUSTODY', custody: true },
  EVIDENCE_LEGAL_HOLD_RELEASED: { category: 'CUSTODY', custody: true },
  EVIDENCE_RETENTION_ASSIGNED: { category: 'CUSTODY', custody: true },
  EVIDENCE_DISPOSAL_REQUESTED: { category: 'CUSTODY', custody: true },
  EVIDENCE_DISPOSAL_APPROVED: { category: 'CUSTODY', custody: true },
  EVIDENCE_DISPOSAL_REJECTED: { category: 'CUSTODY', custody: true },
  EVIDENCE_DISPOSED: { category: 'CUSTODY', custody: true },
  EVIDENCE_DISPOSAL_CANCELLED: { category: 'CUSTODY', custody: true },
  EVIDENCE_DISPOSAL_FAILED: { category: 'CUSTODY', custody: true },
  EVIDENCE_INTEGRITY_CHECK_REQUESTED: { category: 'CUSTODY', custody: true },
  EVIDENCE_TIER_CHANGE_REQUESTED: { category: 'CUSTODY', custody: true },
  EVIDENCE_TIER_CHANGE_FAILED: { category: 'CUSTODY', custody: true },
  EVIDENCE_ACCESS_DENIED: { category: 'CUSTODY', custody: true },
  // Media processing
  MEDIA_PROCESSING_STARTED: { category: 'MEDIA', custody: true },
  MEDIA_PROCESSING_COMPLETED: { category: 'MEDIA', custody: true },
  MEDIA_PROCESSING_FAILED: { category: 'MEDIA', custody: true },
  MEDIA_REPROCESS_REQUESTED: { category: 'MEDIA', custody: true },
  // AI & review
  AI_ANALYSIS_REQUESTED: { category: 'AI', custody: true },
  AI_ANALYSIS_STARTED: { category: 'AI', custody: true },
  AI_ANALYSIS_COMPLETED: { category: 'AI', custody: true },
  AI_ANALYSIS_FAILED: { category: 'AI', custody: true },
  AI_RESULT_APPROVED: { category: 'REVIEW', custody: true },
  AI_RESULT_REJECTED: { category: 'REVIEW', custody: true },
  AI_RESULT_ESCALATED: { category: 'REVIEW', custody: true },
  AI_RESULT_COMMENTED: { category: 'REVIEW', custody: true },
  AI_RESULT_LABEL_CORRECTED: { category: 'REVIEW', custody: true },
  AI_RESULTS_VIEWED: { category: 'REVIEW', custody: true },
  AI_ANALYSIS_CANCELLED: { category: 'AI', custody: true },
  AI_MODEL_UPDATED: { category: 'AI', custody: false },
  AI_TRAINING_EXPORT_REQUESTED: { category: 'AI', custody: false },
  AI_WATCHLIST_EMBEDDED: { category: 'AI', custody: false },
  AI_MODEL_REGISTERED: { category: 'AI', custody: false },
  AI_MODEL_ACTIVATED: { category: 'AI', custody: false },
  AI_MODEL_RETIRED: { category: 'AI', custody: false },
  AI_TRAINING_EXPORTED: { category: 'AI', custody: false },
  AI_WATCHLIST_CHANGED: { category: 'AI', custody: false },
  // Search & investigation
  SEARCH_PERFORMED: { category: 'SEARCH', custody: false },
  SAVED_SEARCH_CHANGED: { category: 'SEARCH', custody: false },
  WORKSPACE_CREATED: { category: 'INVESTIGATION', custody: false },
  WORKSPACE_UPDATED: { category: 'INVESTIGATION', custody: false },
  WORKSPACE_MEMBER_CHANGED: { category: 'INVESTIGATION', custody: false },
  /** sync offset / order / notes of an evidence item inside a workspace changed */
  WORKSPACE_ITEM_UPDATED: { category: 'INVESTIGATION', custody: false },
  WORKSPACE_EVIDENCE_ADDED: { category: 'INVESTIGATION', custody: true },
  WORKSPACE_EVIDENCE_REMOVED: { category: 'INVESTIGATION', custody: true },
  BOOKMARK_CREATED: { category: 'INVESTIGATION', custody: true },
  BOOKMARK_DELETED: { category: 'INVESTIGATION', custody: true },
  ANNOTATION_CREATED: { category: 'INVESTIGATION', custody: true },
  ANNOTATION_UPDATED: { category: 'INVESTIGATION', custody: true },
  ANNOTATION_DELETED: { category: 'INVESTIGATION', custody: true },
  TIMELINE_EVENT_CHANGED: { category: 'INVESTIGATION', custody: false },
  EVIDENCE_RELATION_CHANGED: { category: 'INVESTIGATION', custody: true },
  // Cases
  CASE_CREATED: { category: 'CASE', custody: false },
  CASE_UPDATED: { category: 'CASE', custody: false },
  CASE_NOTE_ADDED: { category: 'CASE', custody: false },
  CASE_MEMBER_CHANGED: { category: 'CASE', custody: false },
  FIR_CREATED: { category: 'CASE', custody: false },
  FIR_UPDATED: { category: 'CASE', custody: false },
  EVIDENCE_LINKED_TO_CASE: { category: 'CUSTODY', custody: true },
  EVIDENCE_UNLINKED_FROM_CASE: { category: 'CUSTODY', custody: true },
  INTEGRATION_SYNC: { category: 'INTEGRATION', custody: false },
  CASE_STATUS_CHANGED: { category: 'CASE', custody: false },
  INTEGRATION_TESTED: { category: 'INTEGRATION', custody: false },
  INTEGRATION_VERIFIED: { category: 'INTEGRATION', custody: false },
  INTEGRATION_API_REQUEST: { category: 'INTEGRATION', custody: false },
  API_CLIENT_SECRET_ROTATED: { category: 'ADMIN', custody: false },
  API_CLIENT_UPDATED: { category: 'ADMIN', custody: false },
  EVIDENCE_DOWNLOAD_LINK_ISSUED: { category: 'CUSTODY', custody: true },
  // Export & sharing
  EXPORT_REQUESTED: { category: 'EXPORT', custody: true },
  EXPORT_APPROVED: { category: 'EXPORT', custody: true },
  EXPORT_REJECTED: { category: 'EXPORT', custody: true },
  EXPORT_GENERATED: { category: 'EXPORT', custody: true },
  EXPORT_FAILED: { category: 'EXPORT', custody: true },
  EXPORT_DOWNLOADED: { category: 'EXPORT', custody: true },
  EXPORT_VERIFIED: { category: 'EXPORT', custody: false },
  EXPORT_REVOKED: { category: 'EXPORT', custody: true },
  SHARE_CREATED: { category: 'SHARE', custody: true },
  SHARE_REVOKED: { category: 'SHARE', custody: true },
  SHARE_ACCESSED: { category: 'SHARE', custody: true },
  SHARE_DOWNLOADED: { category: 'SHARE', custody: true },
  SHARE_PRINTED: { category: 'SHARE', custody: true },
  SHARE_ACCESS_DENIED: { category: 'SHARE', custody: true },
  // Audit / reports / system
  AUDIT_VIEWED: { category: 'SYSTEM', custody: false },
  AUDIT_EXPORTED: { category: 'SYSTEM', custody: false },
  AUDIT_VERIFIED: { category: 'SYSTEM', custody: false },
  AUDIT_CHECKPOINT_CREATED: { category: 'SYSTEM', custody: false },
  CUSTODY_REPORT_GENERATED: { category: 'REPORT', custody: true },
  REPORT_GENERATED: { category: 'REPORT', custody: false },
  ALERT_ACKNOWLEDGED: { category: 'SYSTEM', custody: false },
  ALERT_RESOLVED: { category: 'SYSTEM', custody: false },
  ALERT_RULE_UPDATED: { category: 'ADMIN', custody: false },
  BACKUP_COMPLETED: { category: 'SYSTEM', custody: false },
  RESTORE_COMPLETED: { category: 'SYSTEM', custody: false },
} as const satisfies Record<string, { category: AuditCategory; custody: boolean }>;

export type AuditAction = keyof typeof AUDIT_ACTIONS;
export const CUSTODY_ACTIONS = (Object.keys(AUDIT_ACTIONS) as AuditAction[]).filter((a) => AUDIT_ACTIONS[a].custody);
