apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ksp-vms
resources:
  - ../../../jobs
images:
  - { name: ksp/api, newName: ghcr.io/ksp/api, newTag: 1.0.0 }
  - { name: ksp/ai-worker, newName: ghcr.io/ksp/ai-worker, newTag: 1.0.0 }
