/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<number, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<number, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AiDetections {
  attributes: Generated<Json>;
  bbox_h: number | null;
  bbox_w: number | null;
  bbox_x: number | null;
  bbox_y: number | null;
  confidence: number;
  corrected_label: string | null;
  created_at: Generated<Timestamp>;
  crop_key: string | null;
  embedding: number[] | null;
  evidence_id: string;
  frame_number: Int8 | null;
  frame_time_ms: Int8;
  id: Generated<string>;
  job_id: string;
  label: string;
  model_code: string;
  model_id: string;
  model_version: string;
  review_comment: string | null;
  review_status: Generated<string>;
  reviewed_at: Timestamp | null;
  reviewed_by: string | null;
  task: string;
  threshold: number;
  track_id: string | null;
}

export interface AiJobs {
  created_at: Generated<Timestamp>;
  error: string | null;
  evidence_id: string;
  finished_at: Timestamp | null;
  id: Generated<string>;
  input: Json;
  model_ids: Generated<string[]>;
  params: Generated<Json>;
  progress: Generated<number>;
  requested_by: string;
  started_at: Timestamp | null;
  stats: Generated<Json>;
  status: Generated<string>;
  tasks: string[];
}

export interface AiModels {
  activated_at: Timestamp | null;
  artifact_sha256: string | null;
  artifact_uri: string;
  code: string;
  config: Generated<Json>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  default_threshold: Generated<number>;
  id: Generated<string>;
  labels: Generated<string[]>;
  metrics: Generated<Json>;
  name: string;
  notes: string | null;
  retired_at: Timestamp | null;
  runtime: Generated<string>;
  status: Generated<string>;
  task: string;
  version: string;
}

export interface AiReviewEvents {
  action: string;
  comment: string | null;
  confidence: number;
  corrected_label: string | null;
  created_at: Generated<Timestamp>;
  detection_id: string;
  id: Generated<Int8>;
  model_id: string;
  model_version: string;
  new_status: string;
  previous_status: string;
  reviewer_id: string;
}

export interface AiTrainingExports {
  bucket: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  error: string | null;
  filter: Generated<Json>;
  finished_at: Timestamp | null;
  id: Generated<string>;
  model_id: string | null;
  object_key: string | null;
  sample_count: Generated<number>;
  status: Generated<string>;
  task: string;
}

export interface AiWatchlistEntries {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  embedded_at: Timestamp | null;
  embedding: number[] | null;
  embedding_error: string | null;
  id: Generated<string>;
  image_key: string | null;
  label: string;
  model_id: string | null;
  notes: string | null;
  plate_normalized: string | null;
  watchlist_id: string;
}

export interface AiWatchlists {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  id: Generated<string>;
  kind: string;
  name: string;
  org_unit_id: string;
}

export interface AlertRules {
  code: string;
  config: Generated<Json>;
  enabled: Generated<boolean>;
  id: Generated<string>;
  name: string;
  severity: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface Alerts {
  acknowledged_at: Timestamp | null;
  acknowledged_by: string | null;
  dedupe_key: string | null;
  first_seen_at: Generated<Timestamp>;
  id: Generated<string>;
  last_seen_at: Generated<Timestamp>;
  message: string;
  occurrences: Generated<number>;
  org_unit_id: string | null;
  resolution_note: string | null;
  resolved_at: Timestamp | null;
  resolved_by: string | null;
  resource_id: string | null;
  resource_type: string | null;
  rule_code: string;
  severity: string;
  status: Generated<string>;
  title: string;
}

export interface Annotations {
  author_id: string;
  body: string | null;
  color: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  end_ms: Int8 | null;
  evidence_id: string;
  id: Generated<string>;
  kind: string;
  region: Json | null;
  start_ms: Int8;
  updated_at: Generated<Timestamp>;
  workspace_id: string | null;
}

export interface ApiClientRateWindows {
  api_client_id: string;
  count: Generated<number>;
  window_start: Timestamp;
}

export interface ApiClients {
  allowed_ips: Generated<string[]>;
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  expires_at: Timestamp | null;
  id: Generated<string>;
  last_used_at: Timestamp | null;
  name: string;
  org_unit_id: string;
  rate_limit_per_minute: Generated<number>;
  revoke_reason: string | null;
  revoked_at: Timestamp | null;
  revoked_by: string | null;
  scopes: Generated<string[]>;
  secret_hash: string;
  secret_rotated_at: Timestamp | null;
}

export interface AuditCheckpoints {
  algorithm: string;
  cert_fingerprint: string | null;
  chain_ok: boolean | null;
  created_at: Generated<Timestamp>;
  head_hash: string;
  head_seq: Int8;
  id: Generated<Int8>;
  key_id: string;
  signature: string;
  verified_from_seq: Int8 | null;
}

export interface AuditEvents {
  action: string;
  actor_id: string | null;
  actor_ip: string | null;
  actor_name: string | null;
  actor_type: string;
  case_id: string | null;
  category: string;
  details: Generated<Json>;
  event_id: Generated<string>;
  evidence_id: string | null;
  hash: string;
  occurred_at: Timestamp;
  org_unit_id: string | null;
  outcome: string;
  prev_hash: string;
  resource_id: string | null;
  resource_type: string | null;
  seq: Int8;
  session_id: string | null;
  user_agent: string | null;
}

export interface BackupRuns {
  error: string | null;
  finished_at: Timestamp | null;
  id: Generated<string>;
  kind: string;
  location: string | null;
  sha256: string | null;
  size_bytes: Int8 | null;
  started_at: Generated<Timestamp>;
  status: Generated<string>;
}

export interface Bookmarks {
  created_at: Generated<Timestamp>;
  evidence_id: string;
  id: Generated<string>;
  label: string;
  time_ms: Int8;
  user_id: string;
  workspace_id: string | null;
}

export interface CaseEvidence {
  case_id: string;
  evidence_id: string;
  id: Generated<string>;
  linked_at: Generated<Timestamp>;
  linked_by: string;
  note: string | null;
  unlink_reason: string | null;
  unlinked_at: Timestamp | null;
  unlinked_by: string | null;
}

export interface CaseMembers {
  added_at: Generated<Timestamp>;
  added_by: string | null;
  case_id: string;
  role: Generated<string>;
  user_id: string;
}

export interface CaseNotes {
  author_id: string;
  body: string;
  case_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
}

export interface CaseNumberCounters {
  last_value: Generated<number>;
  org_unit_id: string;
  year: number;
}

export interface Cases {
  case_number: string;
  closed_at: Timestamp | null;
  court_case_number: string | null;
  court_name: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  external_ref: string | null;
  external_system: string | null;
  fir_id: string | null;
  id: Generated<string>;
  investigating_officer_id: string | null;
  opened_at: Generated<Timestamp>;
  org_path: string;
  org_unit_id: string;
  priority: Generated<string>;
  status: Generated<string>;
  supervisor_id: string | null;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface Devices {
  assigned_officer_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  device_type: Generated<string>;
  firmware_version: string | null;
  id: Generated<string>;
  make: string | null;
  model: string | null;
  notes: string | null;
  org_unit_id: string;
  serial_number: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface DisposalRequests {
  authority_ref: string | null;
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  decided_by: string | null;
  decision_note: string | null;
  evidence_id: string;
  executed_at: Timestamp | null;
  execution_attempts: Generated<number>;
  execution_error: string | null;
  execution_result: Json | null;
  id: Generated<string>;
  reason: string;
  requested_by: string;
  status: Generated<string>;
}

export interface Evidence {
  archived_at: Timestamp | null;
  audio_codec: string | null;
  bit_rate: Int8 | null;
  category: string | null;
  container_format: string | null;
  created_at: Generated<Timestamp>;
  description: string | null;
  device_id: string | null;
  device_metadata: Generated<Json>;
  disposed_at: Timestamp | null;
  duplicate_of: string | null;
  duration_ms: Int8 | null;
  evidence_number: string | null;
  frame_rate: Numeric | null;
  gps_latitude: number | null;
  gps_longitude: number | null;
  gps_source: string | null;
  height: number | null;
  id: Generated<string>;
  incident_at: Timestamp | null;
  last_verified_at: Timestamp | null;
  legal_hold: Generated<boolean>;
  legal_hold_at: Timestamp | null;
  legal_hold_by: string | null;
  legal_hold_reason: string | null;
  location_text: string | null;
  media_error: string | null;
  media_status: Generated<string>;
  mime_type: string | null;
  object_lock_until: Timestamp | null;
  officer_id: string | null;
  org_path: string;
  org_unit_id: string;
  original_filename: string;
  probe: Json | null;
  recorded_at: Timestamp | null;
  recorded_end_at: Timestamp | null;
  registered_at: Timestamp | null;
  retain_until: Timestamp | null;
  retention_policy_id: string | null;
  search_text: string | null;
  sha256: string | null;
  sha512: string | null;
  size_bytes: Int8;
  status: Generated<string>;
  status_reason: string | null;
  storage_bucket: string | null;
  storage_key: string | null;
  storage_tier: Generated<string>;
  storage_version_id: string | null;
  title: string | null;
  updated_at: Generated<Timestamp>;
  upload_session_id: string | null;
  uploaded_by: string;
  video_codec: string | null;
  width: number | null;
}

export interface EvidenceDerivatives {
  bucket: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  evidence_id: string;
  height: number | null;
  id: Generated<string>;
  kind: string;
  meta: Generated<Json>;
  mime_type: string | null;
  object_key: string;
  sha256: string | null;
  size_bytes: Int8 | null;
  width: number | null;
}

export interface EvidenceLegalHoldEvents {
  action: string;
  actor_id: string;
  created_at: Generated<Timestamp>;
  evidence_id: string;
  id: Generated<Int8>;
  reason: string;
  storage_hold: string;
  storage_note: string | null;
}

export interface EvidenceNumberCounters {
  last_value: Generated<number>;
  org_unit_id: string;
  year: number;
}

export interface EvidenceRelations {
  created_at: Generated<Timestamp>;
  created_by: string;
  evidence_a: string;
  evidence_b: string;
  id: Generated<string>;
  note: string | null;
  relation: string;
}

export interface EvidenceStorageCopies {
  bucket: string;
  created_at: Generated<Timestamp>;
  evidence_id: string;
  id: Generated<Int8>;
  object_key: string;
  object_lock_until: Timestamp | null;
  sha256: string;
  status: Generated<string>;
  status_note: string | null;
  tier: string;
  updated_at: Generated<Timestamp>;
  version_id: string | null;
}

export interface EvidenceTags {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  evidence_id: string;
  source: Generated<string>;
  tag: string;
}

export interface ExportItems {
  evidence_id: string;
  expected_sha256: string;
  expected_sha512: string | null;
  export_id: string;
  verified_at: Timestamp | null;
  verified_ok: boolean | null;
  verified_sha256: string | null;
  verified_sha512: string | null;
  verify_error: string | null;
}

export interface Exports {
  approved_at: Timestamp | null;
  approved_by: string | null;
  bucket: string | null;
  case_id: string | null;
  completed_at: Timestamp | null;
  court_case_number: string | null;
  court_name: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  decision_note: string | null;
  download_count: Generated<number>;
  error: string | null;
  expires_at: Timestamp | null;
  export_number: string;
  id: Generated<string>;
  ledger_head_hash: string | null;
  ledger_head_seq: Int8 | null;
  manifest: Json | null;
  manifest_sha256: string | null;
  object_key: string | null;
  options: Generated<Json>;
  org_unit_id: string;
  progress: Generated<number>;
  purpose: string;
  recipient: string | null;
  revoke_reason: string | null;
  revoked_at: Timestamp | null;
  revoked_by: string | null;
  sha256: string | null;
  signature: string | null;
  signature_alg: string | null;
  signing_cert_fingerprint: string | null;
  signing_key_id: string | null;
  size_bytes: Int8 | null;
  started_at: Timestamp | null;
  status: Generated<string>;
}

export interface Firs {
  acts_sections: Generated<string[]>;
  brief_facts: string | null;
  complainant: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  external_ref: string | null;
  fir_number: string;
  fir_year: number;
  id: Generated<string>;
  occurred_from: Timestamp | null;
  occurred_to: Timestamp | null;
  org_path: string;
  org_unit_id: string;
  place_of_occurrence: string | null;
  registered_at: Timestamp;
  source: Generated<string>;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface IntegrationSyncLog {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  direction: string;
  error: string | null;
  id: Generated<Int8>;
  operation: string;
  request_ref: string | null;
  status: string;
  summary: Generated<Json>;
  system_id: string;
}

export interface IntegrationSystems {
  adapter: string;
  base_url: string | null;
  code: string;
  config: Generated<Json>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  credentials_ref: string | null;
  enabled: Generated<boolean>;
  id: Generated<string>;
  last_status: string | null;
  last_sync_at: Timestamp | null;
  name: string;
  system_type: string;
  updated_at: Generated<Timestamp>;
  verified: Generated<boolean>;
  verified_at: Timestamp | null;
  verified_by: string | null;
}

export interface IntegrityChecks {
  actual_sha256: string | null;
  checked_at: Generated<Timestamp>;
  error: string | null;
  evidence_id: string;
  expected_sha256: string;
  id: Generated<Int8>;
  ok: boolean;
  requested_by: string | null;
  trigger: string;
}

export interface LoginAttempts {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  ip: string | null;
  reason: string | null;
  success: boolean;
  user_agent: string | null;
  user_id: string | null;
  username: string;
}

export interface Notifications {
  body: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: string;
  link: string | null;
  read_at: Timestamp | null;
  title: string;
  user_id: string;
}

export interface OrgUnits {
  active: Generated<boolean>;
  address: string | null;
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  latitude: number | null;
  longitude: number | null;
  name: string;
  parent_id: string | null;
  path: string;
  phone: string | null;
  unit_type: string;
  updated_at: Generated<Timestamp>;
}

export interface PasswordHistory {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  password_hash: string;
  user_id: string;
}

export interface ProcessingJobs {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  error: string | null;
  evidence_id: string | null;
  finished_at: Timestamp | null;
  id: Generated<string>;
  kind: string;
  progress: Generated<number>;
  queue_job_id: string | null;
  result: Json | null;
  started_at: Timestamp | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  upload_session_id: string | null;
}

export interface RefreshTokens {
  expires_at: Timestamp;
  family_id: string;
  id: Generated<string>;
  issued_at: Generated<Timestamp>;
  parent_id: string | null;
  revoked_at: Timestamp | null;
  session_id: string;
  token_hash: string;
  used_at: Timestamp | null;
}

export interface ReportRuns {
  bucket: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  error: string | null;
  finished_at: Timestamp | null;
  format: string;
  id: Generated<string>;
  object_key: string | null;
  params: Generated<Json>;
  report_type: string;
  row_count: number | null;
  sha256: string | null;
  status: Generated<string>;
}

export interface RetentionPolicies {
  archive_after_days: number | null;
  code: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  is_default: Generated<boolean>;
  long_term_after_days: number | null;
  name: string;
  retention_days: number | null;
  updated_at: Generated<Timestamp>;
}

export interface Roles {
  code: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  is_system: Generated<boolean>;
  name: string;
  permissions: Generated<string[]>;
  updated_at: Generated<Timestamp>;
}

export interface SavedSearches {
  created_at: Generated<Timestamp>;
  criteria: Json;
  id: Generated<string>;
  name: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Sessions {
  absolute_expires_at: Timestamp;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  idle_expires_at: Timestamp;
  ip: string | null;
  last_seen_at: Generated<Timestamp>;
  mfa_verified: Generated<boolean>;
  revoke_reason: string | null;
  revoked_at: Timestamp | null;
  user_agent: string | null;
  user_id: string;
}

export interface ShareAccessLog {
  action: string;
  created_at: Generated<Timestamp>;
  detail: string | null;
  evidence_id: string | null;
  id: Generated<Int8>;
  ip: string | null;
  share_id: string;
  user_agent: string | null;
}

export interface ShareItems {
  evidence_id: string;
  share_id: string;
}

export interface Shares {
  access_code_hash: string | null;
  allow_download: Generated<boolean>;
  allow_original: Generated<boolean>;
  allow_print: Generated<boolean>;
  case_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  download_count: Generated<number>;
  expires_at: Timestamp;
  failed_code_attempts: Generated<number>;
  id: Generated<string>;
  last_accessed_at: Timestamp | null;
  locked_at: Timestamp | null;
  max_views: number | null;
  org_unit_id: string;
  purpose: string;
  recipient_email: string | null;
  recipient_name: string | null;
  recipient_org: string | null;
  recipient_type: string;
  recipient_user_id: string | null;
  revoke_reason: string | null;
  revoked_at: Timestamp | null;
  revoked_by: string | null;
  status: Generated<string>;
  token_hash: string | null;
  view_count: Generated<number>;
  watermark: Generated<boolean>;
}

export interface StorageSnapshots {
  bucket: string;
  capacity_bytes: Int8 | null;
  captured_at: Generated<Timestamp>;
  id: Generated<Int8>;
  object_count: Int8;
  tier: string;
  total_bytes: Int8;
}

export interface SystemSettings {
  key: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  value: Json;
}

export interface TimelineEvents {
  created_at: Generated<Timestamp>;
  created_by: string;
  description: string | null;
  evidence_id: string | null;
  id: Generated<string>;
  occurred_at: Timestamp;
  time_ms: Int8 | null;
  title: string;
  workspace_id: string;
}

export interface UploadBatches {
  client_info: Generated<Json>;
  created_at: Generated<Timestamp>;
  created_by: string;
  id: Generated<string>;
  label: string | null;
  org_unit_id: string;
}

export interface UploadParts {
  etag: string;
  part_number: number;
  received_at: Generated<Timestamp>;
  session_id: string;
  sha256: string;
  size_bytes: Int8;
}

export interface UploadSessions {
  batch_id: string | null;
  chunk_size: number;
  created_at: Generated<Timestamp>;
  created_by: string;
  declared_metadata: Generated<Json>;
  declared_mime: string | null;
  declared_sha256: string | null;
  declared_size: Int8;
  error: string | null;
  evidence_id: string | null;
  expires_at: Timestamp;
  id: Generated<string>;
  org_unit_id: string;
  original_filename: string;
  received_bytes: Generated<Int8>;
  s3_upload_id: string | null;
  staging_bucket: string;
  staging_key: string;
  status: Generated<string>;
  total_chunks: number;
  updated_at: Generated<Timestamp>;
}

export interface UserRoles {
  expires_at: Timestamp | null;
  granted_at: Generated<Timestamp>;
  granted_by: string | null;
  id: Generated<string>;
  org_unit_id: string;
  role_id: string;
  user_id: string;
}

export interface Users {
  badge_number: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  designation: string | null;
  disabled_at: Timestamp | null;
  disabled_reason: string | null;
  email: string | null;
  failed_login_count: Generated<number>;
  full_name: string;
  home_org_unit_id: string;
  id: Generated<string>;
  last_login_at: Timestamp | null;
  last_login_ip: string | null;
  locked_until: Timestamp | null;
  mfa_enabled: Generated<boolean>;
  mfa_enrolled_at: Timestamp | null;
  mfa_pending_secret_enc: string | null;
  mfa_recovery_codes: Generated<string[]>;
  mfa_secret_enc: string | null;
  must_change_password: Generated<boolean>;
  password_changed_at: Timestamp | null;
  password_hash: string | null;
  phone: string | null;
  rank: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  username: string;
}

export interface WorkspaceItems {
  added_at: Generated<Timestamp>;
  added_by: string;
  evidence_id: string;
  id: Generated<string>;
  notes: string | null;
  sort_order: Generated<number>;
  sync_offset_ms: Generated<Int8>;
  workspace_id: string;
}

export interface WorkspaceMembers {
  added_at: Generated<Timestamp>;
  role: Generated<string>;
  user_id: string;
  workspace_id: string;
}

export interface Workspaces {
  case_id: string | null;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  org_unit_id: string;
  owner_id: string;
  status: Generated<string>;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  ai_detections: AiDetections;
  ai_jobs: AiJobs;
  ai_models: AiModels;
  ai_review_events: AiReviewEvents;
  ai_training_exports: AiTrainingExports;
  ai_watchlist_entries: AiWatchlistEntries;
  ai_watchlists: AiWatchlists;
  alert_rules: AlertRules;
  alerts: Alerts;
  annotations: Annotations;
  api_client_rate_windows: ApiClientRateWindows;
  api_clients: ApiClients;
  audit_checkpoints: AuditCheckpoints;
  audit_events: AuditEvents;
  backup_runs: BackupRuns;
  bookmarks: Bookmarks;
  case_evidence: CaseEvidence;
  case_members: CaseMembers;
  case_notes: CaseNotes;
  case_number_counters: CaseNumberCounters;
  cases: Cases;
  devices: Devices;
  disposal_requests: DisposalRequests;
  evidence: Evidence;
  evidence_derivatives: EvidenceDerivatives;
  evidence_legal_hold_events: EvidenceLegalHoldEvents;
  evidence_number_counters: EvidenceNumberCounters;
  evidence_relations: EvidenceRelations;
  evidence_storage_copies: EvidenceStorageCopies;
  evidence_tags: EvidenceTags;
  export_items: ExportItems;
  exports: Exports;
  firs: Firs;
  integration_sync_log: IntegrationSyncLog;
  integration_systems: IntegrationSystems;
  integrity_checks: IntegrityChecks;
  login_attempts: LoginAttempts;
  notifications: Notifications;
  org_units: OrgUnits;
  password_history: PasswordHistory;
  processing_jobs: ProcessingJobs;
  refresh_tokens: RefreshTokens;
  report_runs: ReportRuns;
  retention_policies: RetentionPolicies;
  roles: Roles;
  saved_searches: SavedSearches;
  sessions: Sessions;
  share_access_log: ShareAccessLog;
  share_items: ShareItems;
  shares: Shares;
  storage_snapshots: StorageSnapshots;
  system_settings: SystemSettings;
  timeline_events: TimelineEvents;
  upload_batches: UploadBatches;
  upload_parts: UploadParts;
  upload_sessions: UploadSessions;
  user_roles: UserRoles;
  users: Users;
  workspace_items: WorkspaceItems;
  workspace_members: WorkspaceMembers;
  workspaces: Workspaces;
}
